
# King codes and names
KING_DICT = {
    "k001": "Nabopolassar",
    "k002": "Nebuchadnezzar",
    "k003": "Amel_Marduk",
    "k004": "Nergal-Shar-Usur",
    "k005": "Nabunaid",
    "k006": "Cyrus",
    "k007": "Cambyses",
    "k008": "Darius I",
    "k009": "Xerxes",
    "k010": "Artaxerxes I",
    "k011": "Darius II",
    "k012": "Artaxerxes II",
    "k013": "Artaxerxes III",
    "k014": "Arses",
    "k015": "Darius III",
    "k016": "Alexander III",
    "k017": "Philip Arrahidaeus",
    "k018": "Alexander IV",
    "k019": "Seleucid Era",
}

# Akkadian month names
MONTH_DICT = {
    "1": "Nisanu",
    "2": "Aiaru",
    "3": "Simanu",
    "4": "Duzu",
    "5": "Abu",
    "6": "Ululu",
    "6.5": "Ululu II",
    "7": "Tashritu",
    "8": "Arahsamnu",
    "9": "Kislimu",
    "10": "Tebetu",
    "11": "Shabatu",
    "12": "Addaru",
    "12.5": "Addaru II",
}


BABYLONIAN_STAR_CATALOG = {
    "Sirius": {
        "ra0": (6, 45, 8.917),
        "dec0": (-16, -42, -58.00),
        "pm_ra": -0.54601,
        "pm_dec": -1.22307,
        "arc_of_vision": 11.5,
        "cuneiform_name": "mul.KAK.SI.SÁ",
        "cuneiform_unicode": "𒀯𒆕𒋛𒊓",
        "transliteration": "Šukūdu",
        "meaning": "The Arrow",
        "type": "both",
        "V": -1.46 ,
        "(B-V)": 0.0 ,
        "comment": "Pure white. The brightest star in the sky."
    },
    "Regulus": {
        "ra0": (10, 8, 22.311),
        "dec0": (11, 58, 1.95),
        "pm_ra": -0.248,
        "pm_dec": 0.005,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.LUGAL",
        "cuneiform_unicode": "𒀯𒈗",
        "transliteration": "Šaru",
        "meaning": "The King",
        "type": "both",
        "V": 1.35,
        "(B-V)": -0.11,
        "comment": "Blue-white (Will rise less easily at twilight)."
    },
    "Spica": {
        "ra0": (13, 25, 11.579),
        "dec0": (-11, -9, -40.76),
        "pm_ra": -0.042,
        "pm_dec": -0.028,
        "arc_of_vision": 11.0,
        "cuneiform_name": "mul.AB.SÍN",
        "cuneiform_unicode": "𒀯𒀳",
        "transliteration": "Šeru'u",
        "meaning": "The Furrow",
        "type": "both",
        "V": 0.98,
        "(B-V)": -0.23,
        "comment": "Intense blue (Very sensitive to extinction)."
    },
    "Aldebaran": {
        "ra0": (4, 35, 55.239),
        "dec0": (16, 30, 33.49),
        "pm_ra": 0.063,
        "pm_dec": -0.189,
        "arc_of_vision": 11.5,
        "cuneiform_name": "mul.is LI.SI",
        "cuneiform_unicode": "𒀯𒄑𒇷𒋛",
        "transliteration": "Is lē",
        "meaning": "The Jaw of the Bull",
        "type": "both",
        "V": 0.85,
        "(B-V)": 1.54,
        "comment": "Orange giant (Resistes haze very well)."

    },
    "Antares": {
        "ra0": (16, 29, 24.459),
        "dec0": (-26, -25, -55.21),
        "pm_ra": -0.010,
        "pm_dec": -0.023,
        "arc_of_vision": 13.0,
        "cuneiform_name": "mul.GAB.GÍR.TAB",
        "cuneiform_unicode": "𒀯𒆕𒄈𒋰",
        "transliteration": "Irtu nizu qatru",
        "meaning": "The Breast of the Scorpion",
        "type": "both",
        "V": 1.06,
        "(B-V)": 1.83,
        "comment": "Red supergiant (Maximum resistance to extinction). Variable."
    },
    "Pollux": {
        "ra0": (7, 45, 18.949),
        "dec0": (28, 1, 34.31),
        "pm_ra": -0.62599,
        "pm_dec": -0.04599,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.MAŠ.TAB.BA.GAL.GAL",
        "cuneiform_unicode": "𒀯𒈦𒋰𒁀𒃲𒃲",
        "transliteration": "Māšu rabûtu",
        "meaning": "The Great Twin",
        "type": "both",
        "V": 1.14,
        "(B-V)": 1.00,
        "comment": "Orange-yellow giant."
    },
    "Procyon": {
        "ra0": (7, 39, 18.119),
        "dec0": (5, 13, 29.95),
        "pm_ra": -0.71658,
        "pm_dec": -1.03458,
        "arc_of_vision": 11.5,
        "cuneiform_name": "mul.DAR.LUGAL",
        "cuneiform_unicode": "𒀯𒋻𒈗",
        "transliteration": "Tarlugallu",
        "meaning": "The King's Rooster",
        "type": "both",
        "V": 0.34,
        "(B-V)": 0.42,
        "comment": "Yellow-white."
    },
    "Capella": {
        "ra0": (5, 16, 41.359),
        "dec0": (45, 59, 52.77),
        "pm_ra": 0.441,
        "pm_dec": -0.433,
        "arc_of_vision": 11.0,  # Highly northern star, very bright
        "cuneiform_name": "mul.ÁŠ.IKU",
        "cuneiform_unicode": "𒀯𒀸𒃷",
        "transliteration": "Iku",
        "meaning": "The Field",
        "type": "both",
        "V": 0.08,
        "(B-V)": 0.80,
        "comment": "Yellow (Spectrum similar to the Sun)."

    },
    "Arcturus": {
        "ra0": (14, 15, 39.672),
        "dec0": (19, 10, 56.67),
        "pm_ra": -1.093,
        "pm_dec": -1.999,
        "arc_of_vision": 11.0,  # Extremely large proper motion
        "cuneiform_name": "mul.ŠU.PA",
        "cuneiform_unicode": "𒀯𒋗𒉺",
        "transliteration": "Šupû",
        "meaning": "The Brilliant One",
        "type": "both",
        "V": -0.05,
        "(B-V)": 1.23,
        "comment": "Orange giant. Very bright in the north."
    },
    "Beta_Librae": {        # β Longitude (Beta Librae)
        "ra0": (15, 17, 0.446),
        "dec0": (-9, -22, -58.33),
        "pm_ra": -0.101,
        "pm_dec": -0.068,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.RÍN.šá.SI",
        "cuneiform_unicode": "𒀯𒂟𒊹𒋛",
        "transliteration": "Zibanītu šá iltānu",
        "meaning": "The Northern Horn of the Balance",
        "type": "normal_star",
        "V": 2.61,
        "(B-V)": -0.11,
        "comment": "Blue-white (Zubeneschamali)."
    },
    "Alpha_Librae": {     # α Longitude (Alpha Librae)
        "ra0": (14, 50, 41.258),
        "dec0": (-16, -2, -29.80),
        "pm_ra": -0.104,
        "pm_dec": -0.070,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.RÍN.šá.u-lu",
        "cuneiform_unicode": "𒀯𒂟𒊹𒌋𒇻",
        "transliteration": "Zibanītu šá šūt-āli",
        "meaning": "The Southern Horn of the Balance",
        "type": "normal_star",
        "V": 2.75,
        "(B-V)": 0.15,
        "comment": "White (Zubenelgenubi). Spectroscopic binary."
    },
    "Alcyone": {                 # Pleiades
        "ra0": (3, 47, 29.077),
        "dec0": (24, 6, 18.49),
        "pm_ra": 0.019,
        "pm_dec": -0.043,
        "arc_of_vision": 13.0,  # Fainter cluster, requires higher arc of vision
        "cuneiform_name": "mul.MUL",
        "cuneiform_unicode": "𒀯𒀯",
        "transliteration": "Zappu",
        "meaning": "The Bristle / The Star Cluster",
        "type": "both",
        "V": 2.85,
        "(B-V)": -0.09,
        "comment": "Blue-white (The brightest star in the Pleiades)."
    },
    "Castor": {
        "ra0": (7, 34, 35.998),
        "dec0": (31, 53, 17.82),
        "pm_ra": -0.191,
        "pm_dec": -0.144,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.MAŠ.TAB.BA.TUR.TUR",
        "cuneiform_unicode": "𒀯𒈦𒋰𒁀𒌉𒌉",
        "transliteration": "Māšu ṣahrūtu",
        "meaning": "The Small Twin of the North",
        "type": "both",
        "V": 1.58,
        "(B-V)": 0.03,
        "comment": "White."
    },
    "Eta_Piscium": {            # η Piscium
        "ra0": (1, 31, 29.011),
        "dec0": (15, 20, 45.02),
        "pm_ra": 0.026,
        "pm_dec": -0.012,
        "arc_of_vision": 13.0,  # 3rd magnitude star, crucial for Pisces boundary
        "cuneiform_name": "mul.KUN.MEŠ",
        "cuneiform_unicode": "𒀯𒆲𒔼",
        "transliteration": "Zibbātu",
        "meaning": "The Tails (of the Fishes)",
        "type": "normal_star",
        "V": 3.62,
        "(B-V)": 1.40,
        "comment": "Orange fluid giant (Faint brightness, critical for visibility)."
    },
    "Alhena": {    # γ Geminorum (Alhena)
        "ra0": (6, 37, 42.711),
        "dec0": (16, 23, 57.41),
        "pm_ra": -0.005,
        "pm_dec": -0.066,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.ALLA šá mi-ḫat rēši",
        "cuneiform_unicode": "𒀯𒀠𒆷𒊭𒈪𒄩𒀜𒊕",
        "transliteration": "Alluttu šá mihat rēši",
        "meaning": "The Crab opposite the Head",
        "type": "normal_star",
        "V": 1.93,
        "(B-V)": 0.00,
        "comment": "White ($\\gamma$ Geminorum)."
    },
    "Mekbuda": {    # ζ Geminorum (Mekbuda)
        "ra0": (7, 4, 6.531),
        "dec0": (20, 34, 13.07),
        "pm_ra": -0.007,
        "pm_dec": -0.010,
        "arc_of_vision": 12.5,
        "cuneiform_name": "mul.MAŠ.TAB.BA šá u-lu šu-ut rēši",
        "cuneiform_unicode": "𒀯𒈦𒋰𒁀𒊭𒌋𒌋𒋗𒌓𒊕",
        "transliteration": "Māšu šá šūt-āli šut rēši",
        "meaning": "The Southern Twin towards the Head",
        "type": "normal_star",
        "V": 4.00,
        "(B-V)": 0.75,
        "comment": "Yellow supergiant ($\\zeta$ Geminorum). Cepheid variable."
    },
    "Epsilon_Leonis": {           # ε Leonis
        "ra0": (9, 45, 51.066),
        "dec0": (23, 46, 27.27),
        "pm_ra": -0.053,
        "pm_dec": -0.025,
        "arc_of_vision": 12.5,
        "cuneiform_name": "mul.UR.GU.LA šá rēš ari",
        "cuneiform_unicode": "𒀯𒌨𒄖𒆷𒊭𒊕𒀀𒊑",
        "transliteration": "Urgulû šá rēš ari",
        "meaning": "The Lion's Head / The Lion at the Head",
        "type": "normal_star",
        "V": 2.97,
        "(B-V)": 0.84,
        "comment": "Yellow giant."
    },
    "Hamal": {       # α Arietis (Hamal)
        "ra0": (2, 7, 10.403),
        "dec0": (23, 27, 44.70),
        "pm_ra": 0.231,
        "pm_dec": -0.147,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.LÚ.ḪUN.GÁ",
        "cuneiform_unicode": "𒀯𒇽𒂠𒂷",
        "transliteration": "Agru",
        "meaning": "The Hired Man (Aries)",
        "type": "normal_star",
        "V": 2.01,
        "(B-V)": 1.15,
        "comment": "Orange giant ($\\alpha$ Arietis)."
    },
# --- MUL.APIN EXTENSION (To be merged into BABYLONIAN_STAR_CATALOG) ---

    # 1. UPDATES FOR EXISTING STARS (Change "type" to "both")
    # Please update the "type" field of these stars in your current dictionary:
    # "Sirius"          -> "type": "both" (mul.KAK.SI.SÁ / Arrow)
    # "Regulus"         -> "type": "both" (mul.LUGAL / King)
    # "Spica"           -> "type": "both" (mul.AB.SÍN / Furrow)
    # "Aldebaran"       -> "type": "both" (mul.is LI.SI / Jaw of the Bull)
    # "Antares"         -> "type": "both" (mul.GAB.GÍR.TAB / Breast of the Scorpion)
    # "Alcyone"         -> "type": "both" (mul.MUL / The Stars / Pleiades)

    # 2. NEW MUL.APIN ADDITIONS
    "Vega": {
        "ra0": (18, 36, 56.336),
        "dec0": (38, 47, 1.28),
        "pm_ra": 0.201,
        "pm_dec": 0.287,
        "arc_of_vision": 11.0,
        "cuneiform_name": "mul.BALAG.AN.NA",
        "cuneiform_unicode": "𒀯𒁆𒀭𒈾",
        "transliteration": "Uza",
        "meaning": "The Goat / The Heavenly Lyre",
        "type": "mul_apin",
        "start_month": 10,
        "V": 0.03,
        "(B-V)": 0.00,
        "comment": "Pure white. Photometric calibration standard."
    },
    "Altair": {
        "ra0": (19, 50, 46.999),
        "dec0": (8, 52, 5.96),
        "pm_ra": 0.536,
        "pm_dec": 0.386,
        "arc_of_vision": 11.5,
        "cuneiform_name": "mul.TI_8.MUŠEN",
        "cuneiform_unicode": "𒀯𒀉𒄷",
        "transliteration": "Erû",
        "meaning": "The Eagle",
        "type": "mul_apin",
        "start_month": 10,
        "V": 0.76,
        "(B-V)": 0.22,
        "comment": "White. Hyperfast rotation."
    },
    "Arneb": {
        "ra0": (5, 32, 43.817),
        "dec0": (-17, -49, -20.24),
        "pm_ra": 0.003,
        "pm_dec": -0.001,
        "arc_of_vision": 13.0,
        "cuneiform_name": "mul.KA_5.A",
        "cuneiform_unicode": "𒀯𒈜𒀀",
        "transliteration": "Šelebu",
        "meaning": "The Fox",
        "type": "mul_apin",
        "V": 2.58,
        "(B-V)": 0.21,
        "comment": "White supergiant ($\\alpha$ Leporis)."
    },
    "Betelgeuse": {
        "ra0": (5, 55, 10.305),
        "dec0": (7, 24, 25.43),
        "pm_ra": 0.027,
        "pm_dec": 0.011,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.SIPA.ZI.AN.NA",
        "cuneiform_unicode": "𒀯𒉺𒇻𒍣𒀭𒈾",
        "transliteration": "Shitaddalu",
        "meaning": "The True Shepherd of Anu (Orion)",
        "type": "mul_apin",
        "V": 0.50,
        "(B-V)": 1.85,
        "comment": "Red supergiant. Highly variable (0.00 to 1.60)."
    },
    "Fomalhaut": {
        "ra0": (22, 57, 39.046),
        "dec0": (-29, -37, -20.05),
        "pm_ra": 0.329,
        "pm_dec": -0.165,
        "arc_of_vision": 12.5,
        "cuneiform_name": "mul.KU_6",
        "cuneiform_unicode": "𒀯𒄩",
        "transliteration": "Nūnu",
        "meaning": "The Fish",
        "type": "mul_apin",
        "V": 1.16,
        "(B-V)": 0.09,
        "comment": "White. Too southern for the Mesopotamian twilight."
    },
    "Menkar": {
        "ra0": (3, 2, 16.773),
        "dec0": (4, 5, 23.06),
        "pm_ra": -0.012,
        "pm_dec": -0.078,
        "arc_of_vision": 13.0,
        "cuneiform_name": "mul.mi-in-da-nu",
        "cuneiform_unicode": "𒀯𒈪𒅔𒁕𒉡",
        "transliteration": "Kūbū",
        "meaning": "The Whale / Monster of the Sea",
        "type": "mul_apin",
        "V": 2.54,
        "(B-V)": 1.64,
        "comment": "Red giant ($\\alpha$ Ceti). Excellent colorfastness."
    },
# --- SECOND MUL.APIN EXTENSION ---

    "Dubhe": {
        "ra0": (11, 3, 43.671),
        "dec0": (61, 45, 3.72),
        "pm_ra": -0.136,
        "pm_dec": -0.035,
        "arc_of_vision": 10.0,  # Highly circumpolar, low extinction angle needed
        "cuneiform_name": "mul.MAR.GÍD.DA",
        "cuneiform_unicode": "𒀯𒈥𒁍𒁕",
        "transliteration": "Eriqqānītu",
        "meaning": "The Wagon (Big Dipper / Ursa Major)",
        "type": "mul_apin",
        "start_month": 10,
        "V": 1.79,
        "(B-V)": 1.07,
        "comment": "Orange giant (Circumpolar in your tests)."
    },
    "Polaris": {
        "ra0": (2, 31, 49.094),
        "dec0": (89, 15, 50.8),
        "pm_ra": 0.044,
        "pm_dec": -0.012,
        "arc_of_vision": 9.0,   # Near the celestial pole
        "cuneiform_name": "mul.AN.TA.GUB.BA",
        "cuneiform_unicode": "𒀯𒀭𒋫𒁺𒁀",
        "transliteration": "Muzlilu",
        "meaning": "The Standing Heavenly Star / Star of Anu",
        "type": "mul_apin",
        "V": 1.97,
        "(B-V)": 0.60,
        "comment": "Yellow supergiant. Classic Cepheid (Declination >85°)."
    },
    "Canopus": {
        "ra0": (6, 23, 57.110),
        "dec0": (-52, -41, -44.38),
        "pm_ra": 0.020,
        "pm_dec": 0.024,
        "arc_of_vision": 13.5,  # Southern horizon, extreme atmospheric extinction
        "cuneiform_name": "mul.NUN.KI",
        "cuneiform_unicode": "𒀯𒉣𒆠",
        "transliteration": "Nunki / Nunu",
        "meaning": "The Star of Eridu (South Channel)",
        "type": "mul_apin",
        "V": -0.74,
        "(B-V)": 0.15,
        "comment": "Yellow-white supergiant. The second brightest."
    },
    "Deneb": {
        "ra0": (20, 41, 25.915),
        "dec0": (45, 16, 49.22),
        "pm_ra": 0.002,
        "pm_dec": 0.002,
        "arc_of_vision": 11.5,
        "cuneiform_name": "mul.UD.KA.DUH.A",
        "cuneiform_unicode": "𒀯𒌓𒅗𒁺𒀀",
        "transliteration": "Udkaduhû",
        "meaning": "The Demon with the Gaping Mouth (Cygnus)",
        "type": "mul_apin",
        "V": 1.25,
        "(B-V)": 0.09,
        "comment": "White supergiant (Circumpolar)."
    },
    "Rigel": {
        "ra0": (5, 14, 32.272),
        "dec0": (-8, -12, -5.89),
        "pm_ra": 0.001,
        "pm_dec": -0.001,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.GIR_2.an-na",
        "cuneiform_unicode": "𒀯𒄈𒀭𒈾",
        "transliteration": "Shepē-shūt-Anu",
        "meaning": "The Star of the Heel (Orion's Foot)",
        "type": "mul_apin",
        "V": 0.13,
        "(B-V)": -0.03,
        "comment": "Blue supergiant (Enormous brightness, great blue extinction)."
    },
    "Alphecca": {
        "ra0": (15, 34, 41.268),
        "dec0": (26, 42, 52.89),
        "pm_ra": 0.120,
        "pm_dec": -0.089,
        "arc_of_vision": 12.0,
        "cuneiform_name": "mul.BALAG.IŠTAR",
        "cuneiform_unicode": "𒀯𒁆𒀭𒈹",
        "transliteration": "Panzur",
        "meaning": "The Tiara of Ishtar / The Dignitary Lyre",
        "type": "mul_apin",
        "V": 2.22,
        "(B-V)": 0.00,
        "comment": "White ($\\alpha$ Coronae Borealis)."
    }
}
